name: Run Unit Tests

on:
  push:
    branches: [ dev ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m pytest
    
    - name: Create Pull Request to main
      if: success()
      id: cpr
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.PAT }}
        commit-message: Pull Request to main
        committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: dev
        delete-branch: false
        title: '[AUTO] Pull Request to main'
        body: |
          Pull Request to main
          - Auto-generated by workflow
        labels: |
          automated pr
        assignees: ghhwer
        reviewers: ghhwer
        milestone: 1
        draft: false
