name: Run Unit Tests

on:
  push:
    branches: [ dev ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m pytest
    
    - name: Create Pull Request to main
      if: success()
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Update main"
        branch: "create-pr/main"
        base: "main"
        title: "Update main"
        body: "Update main with changes from dev"

    - name: Create Pull Request to published
      if: success()
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Update published"
        branch: "create-pr/published"
        base: "published"
        title: "Update published"
        body: "Update published with changes from dev"